apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sample-node-ayeaye
  namespace: $ENVIRONMENT
spec:
  # 3 Pods should exist at all times.
  replicas: $REPLICAS
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sample-node-ayeaye
        env: $ENVIRONMENT
    spec:
      containers:
      - name: sample-node-ayeaye
        image: $IMAGE_URL:$IMAGE_TAG
        ports:
        - containerPort: $PORT
        env:
        - name: ENVIRONMENT
          value: "$ENVIRONMENT"
        - name: PORT
          value: "$PORT"
        resources:
          requests:
            memory: $MEMORY
            cpu: $CPUSHARES
