jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# runCI job that builds and pushes artifact to S3
  - name: deploy-kubernetes-runcli_runCI
    type: runCI
    steps:
      - OUT: deploy-kubernetes-runcli-img
    flags:
      - deploy-kubernetes-runcli

# TEST deployment to Kube cluster on AWS
  - name: deploy-kubernetes-runcli-test
    type: runCLI
    steps:
      - IN: deploy-kubernetes-runcli-repo
        switch: off
      - IN: deploy-kubernetes-runcli-cli-kubectl
      - IN: deploy-kubernetes-runcli-img
      - IN: deploy-kubernetes-runcli-params-test
      - TASK:
        - script: source $SHIPDEMOPARAMSTEST_STATE/params
        - script: echo "deploying to Kubernetes cluster..."
        - script: kubectl config use-context $CLUSTER
        - script: pushd $SHIPDEMOREPO_STATE
        - script: shippable_replace kube-deploy.yaml
        - script: kubectl apply -f kube-deploy.yaml 
        - script: kubectl rollout status deployments sample-node-ayeaye
    flags:
      - deploy-kubernetes-runcli

# PROD deployment to Kube cluster on AWS
  - name: deploy-kubernetes-runcli-prod
    type: runCLI
    steps:
      - IN: deploy-kubernetes-runcli-test
        switch: off
      - IN: deploy-kubernetes-runcli-repo
        switch: off
      - IN: deploy-kubernetes-runcli-cli-kubectl
      - IN: deploy-kubernetes-runcli-params-prod
      - TASK:
        - script: . $SHIPDEMOREPO_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $SHIPDEMOREPO_PATH/gitRepo/pipeline/deploy.sh
    flags:
      - deploy-kubernetes-runcli
