jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# runCI job that builds and pushes artifact to S3
  - name: node-dockerhub-runcli-kubernetes-kubectl_runCI
    type: runCI
    steps:
      - OUT: shipdemo-img

# TEST deployment to Kube cluster on AWS
  - name: shipdemo-kubectl-deploy-test
    type: runCLI
    steps:
      - IN: shipdemo-repo
        switch: off
      - IN: shipdemo-cli-kubectl
      - IN: shipdemo-img
      - IN: shipdemo-params-test
      - TASK:
        - script: source $SHIPDEMOPARAMSTEST_STATE/params
        - script: echo "deploying to Kubernetes cluster..."
        - script: kubectl config use-context $CLUSTER
        - script: pushd $SHIPDEMOREPO_STATE
        - script: shippable_replace kube-deploy.yaml
        - script: kubectl apply -f kube-deploy.yaml 
        - script: kubectl rollout status deployments sample-node-ayeaye
    flags:
      - runCLI-kubernetes-kubectl

# PROD deployment to Kube cluster on AWS
  - name: shipdemo-kubectl-deploy-prod
    type: runCLI
    steps:
      - IN: shipdemo-kubectl-deploy-test
        switch: off
      - IN: shipdemo-repo
        switch: off
      - IN: shipdemo-cli-kubectl
      - IN: shipdemo-params-prod
      - TASK:
        - script: . $SHIPDEMOREPO_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $SHIPDEMOREPO_PATH/gitRepo/pipeline/deploy.sh
    flags:
      - runCLI-kubernetes-kubectl
