jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# runCI job that builds and pushes artifact to S3
  - name: deploy-kubernetes-runcli_runCI
    type: runCI
    steps:
      - OUT: deploy_kubernetes_runcli_img
    flags:
      - deploy_kubernetes_runcli

# TEST deployment to Kube cluster on AWS
  - name: deploy_kubernetes_runcli_test
    type: runCLI
    steps:
      - IN: deploy_kubernetes_runcli_repo
        switch: off
      - IN: deploy_kubernetes_runcli_cli_kubectl
      - IN: deploy_kubernetes_runcli_img
      - IN: deploy_kubernetes_runcli_params_test
      - TASK:
        - script: source $DEPLOY_KUBERNETES_RUNCLI_PARAMS_TEST_STATE
        - script: printenv
        - script: echo "deploying to Kubernetes cluster..."
        - script: pushd $DEPLOY_KUBERNETES_RUNCLI_REPO_STATE
        - script: shippable_replace kube-deploy.yaml
        - script: kubectl apply -f kube-deploy.yaml 
        - script: kubectl rollout status deployments sample_node_ayeaye
    flags:
      - deploy_kubernetes_runcli

# PROD deployment to Kube cluster on AWS
  - name: deploy_kubernetes_runcli_prod
    type: runCLI
    steps:
      - IN: deploy_kubernetes_runcli_test
        switch: off
      - IN: deploy_kubernetes_runcli_repo
        switch: off
      - IN: deploy_kubernetes_runcli_cli_kubectl
      - IN: deploy_kubernetes_runcli_params_prod
      - TASK:
        - script: . $DEPLOY_KUBERNETES_RUNCLI_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $DEPLOY_KUBERNETES_RUNCLI_PATH/gitRepo/pipeline/deploy.sh
    flags:
      - deploy_kubernetes_runcli
