jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# runCI job that builds and pushes artifact to S3
  - name: deploy-kubernetes-runcli_runCI
    type: runCI
    steps:
      - OUT: deploy_kubernetes_runcli_img
    flags:
      - deploy_kubernetes_runcli

# TEST deployment to Kube cluster on AWS
  - name: deploy_kubernetes_runcli_test
    type: runCLI
    steps:
      - IN: deploy_kubernetes_runcli_repo
        switch: off
      - IN: deploy_kubernetes_runcli_cli_kubectl
      - IN: deploy_kubernetes_runcli_img
      - IN: deploy_kubernetes_runcli_params_test
      - TASK:
        # set environment variables
        - script: |
            set -a
            source $DEPLOY_KUBERNETES_RUNCLI_PARAMS_TEST_STATE
            IMAGE_URL=$DEPLOY_KUBERNETES_RUNCLI_IMG_SOURCENAME
            IMAGE_TAG=$DEPLOY_KUBERNETES_RUNCLI_IMG_VERSIONNAME
            set +a
        - script: echo "deploying to Kubernetes cluster..."
        # update kubernetes yaml file(s)
        - script: cd $DEPLOY_KUBERNETES_RUNCLI_REPO_STATE
        - script: shippable_replace kube-deploy.yaml
        - script: cat kube-deploy.yaml
        # deploy to cluster and verify success
        - script: kubectl apply -f kube-deploy.yaml 
        - script: kubectl rollout status deployments sample-node-ayeaye --namespace $ENVIRONMENT
        # save image state
        - script: >
            echo -e "IMAGE_TAG=$IMAGE_TAG"\n 
            "IMAGE_URL=$IMAGE_URL"
            > $DEPLOY_KUBERNETES_RUNCLI_TEST_STATE/latest_test_deploy.env
    flags:
      - deploy_kubernetes_runcli

# PROD deployment to Kube cluster on AWS
  - name: deploy_kubernetes_runcli_prod
    type: runCLI
    steps:
      - IN: deploy_kubernetes_runcli_test
        switch: off
      - IN: deploy_kubernetes_runcli_repo
        switch: off
      - IN: deploy_kubernetes_runcli_cli_kubectl
      - IN: deploy_kubernetes_runcli_params_prod
      - TASK:
        # set environment variables
        - script: |
            set -a
            source $DEPLOY_KUBERNETES_RUNCLI_TEST_STATE/latest_test_deploy.env
            source $DEPLOY_KUBERNETES_RUNCLI_PARAMS_PROD_STATE
            set +a
        - script: echo "deploying to Kubernetes cluster..."
        # update kubernetes yaml file(s)
        - script: cd $DEPLOY_KUBERNETES_RUNCLI_REPO_STATE
        - script: shippable_replace kube-deploy.yaml
        - script: cat kube-deploy.yaml
        # deploy to cluster and verify success
        - script: kubectl apply -f kube-deploy.yaml 
        - script: kubectl rollout status deployments sample-node-ayeaye --namespace $ENVIRONMENT
        # save image state
        - script: echo -e "IMAGE_TAG=$IMAGE_TAG" > $DEPLOY_KUBERNETES_RUNCLI_PROD_STATE/latest_prod_deploy.env
    flags:
      - deploy_kubernetes_runcli
