apiVersion: v1
kind: Service
metadata:
  name: service-sample-node-ayeaye-test
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: sample-node-ayeaye
    env: test
  type: LoadBalancer
